
nelmio_cors:
        paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            max_age: 3600
    #     origin_regex: true
    #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    #     allow_headers: ['Content-Type', 'Authorization']
    #     max_age: 3600
    # paths:
    #     '^/': ~
    # defaults:
    #     origin_regex: true
    #     allow_origin: ['^https://localhost:[0-9]+']
    #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    #     allow_headers: ['Access-Control-Allow-Headers','Accept','Authorization','Cache-Control','Content-Type','DNT','If-Modified-Since','Keep-Alive','Origin','User-Agent','X-Requested-With']
    #     expose_headers: ['Authorization']
    #     max_age: 3600
    # paths:
    #     '^/': ~
    # paths:
    #     '^/':
    #         allow_origin: ['*']
    #         allow_headers: ['*']
    #         allow_methods: ['*']
    #         max_age: 3600
        # defaults:
        #     allow_credentials: false
        #     allow_origin: []
        #     allow_headers: []
        #     allow_methods: []
        #     expose_headers: []
        #     max_age: 0
        #     hosts: []
        #     origin_regex: false
        #     forced_allow_origin_value: ~
        # paths:
            # '^/api/':
            #     allow_origin: ['*']
            #     allow_headers: ['X-Custom-Auth']
            #     allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            #     max_age: 3600
            # '^/':
            #     origin_regex: true
            #     allow_origin: ['^http://localhost:[0-9]+']
            #     allow_headers: ['X-Custom-Auth']
            #     allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            #     max_age: 3600
                # hosts: ['^api\.']
# nelmio_cors:
    # defaults:
    #     origin_regex: true
    #     allow_origin: ['*']
    #     allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    #     allow_headers: ['Accept','Authorization','Cache-Control','Content-Type','DNT','If-Modified-Since','Keep-Alive','Origin','User-Agent','X-Requested-With']
    #     expose_headers: ['Authorization']
    #     max_age: 3600
    # paths:
    #     '^/': ~